# dubbo
dubbo:
  application:
    name: hueason-store-console
  registry:
#    address: N/A
    address: 192.168.126.1:2181
    protocol: zookeeper
  annotation:
    package: com.hueason.console.controller
  consumer:
    timeout: 6000
    check: false

server:
  port: 8088

spring:
  thymeleaf:
    cache: false
    http:
      multipart:
        maxFileSize: 10Mb
        maxRequestSize: 10Mb

# swagger2
swagger2.package: com.hueason.console.controller